// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEg3diAfcW1ks0mZJlCxsXeowMcu6wRXc',
    appId: '1:865696246993:web:81ec863c611c4e923329f0',
    messagingSenderId: '865696246993',
    projectId: 'wedding-collection-9b440',
    authDomain: 'wedding-collection-9b440.firebaseapp.com',
    storageBucket: 'wedding-collection-9b440.firebasestorage.app',
    measurementId: 'G-3C6HLCL3RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UWXmXP0R_CF5efMM4sDAmtvIpvD_oKQ',
    appId: '1:865696246993:android:c494568f2675eda53329f0',
    messagingSenderId: '865696246993',
    projectId: 'wedding-collection-9b440',
    storageBucket: 'wedding-collection-9b440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaB5Y1ePNbcKauD9vyC8lFFJiijf1hSxo',
    appId: '1:865696246993:ios:b96774b91a086c053329f0',
    messagingSenderId: '865696246993',
    projectId: 'wedding-collection-9b440',
    storageBucket: 'wedding-collection-9b440.firebasestorage.app',
    iosBundleId: 'com.example.weddingCollectionNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaB5Y1ePNbcKauD9vyC8lFFJiijf1hSxo',
    appId: '1:865696246993:ios:b96774b91a086c053329f0',
    messagingSenderId: '865696246993',
    projectId: 'wedding-collection-9b440',
    storageBucket: 'wedding-collection-9b440.firebasestorage.app',
    iosBundleId: 'com.example.weddingCollectionNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEg3diAfcW1ks0mZJlCxsXeowMcu6wRXc',
    appId: '1:865696246993:web:f2dbdd5ec59a78a33329f0',
    messagingSenderId: '865696246993',
    projectId: 'wedding-collection-9b440',
    authDomain: 'wedding-collection-9b440.firebaseapp.com',
    storageBucket: 'wedding-collection-9b440.firebasestorage.app',
    measurementId: 'G-FP2NRN7M8Y',
  );
}
